### ISSUE TITLE
Add leveling system

### ISSUE THREAD

**Issue by tboyjwilz** [MassiveCraft/Vampire#58]
I absolutely love this plugin as it brings more role-play into minecraft.

However, at the moment, there is no difference between the new-born vampires and the older vampires and i think that there should be some sort of leveling system that makes a vampire better somehow.

The way to level up could be praying at the alter of darkness since at the moment, praying there doesn't do anything but give you temporary blindness. Praying there should be available once a minecraft day or 2 so as to prevent Spam leveling.

Leveling up can do a variety of things like increasing the base part of the irradiation speed to grow a slight immune system to the sun (but not too much).
You could also level a resistance to wooden stakes, one of a vampires biggest weaknesses. You could also level small things like leveling jumping hight or unarmed combat damage.

Leveling up may result in only one of these aspects increasing or it could give you some sort of vampire currency like blood points (for example) and then you would be able to spend those points to buy the next level of an aspect. This will give some mystery to how dangerous a vampire is when you are thinking of attacking one, will wooden weapons work? What if they have leveled their resistance to stakes? A stick wont do much damage then..

So with a leveling system, a new vampire wouldn't be instantly as good as a more experienced vampire and there would be more mystery to how dangerous a vampire really is.

Thanks for reading my suggestion =)

**Comment by ulumulu1510** [comment]
While we see the possible benefits of a leveling system, it is incredibly hard to maintain and balance. Balancing Vampires per se is hard to balance, but a leveling system would be even harder to do. Thus we have decided against such a leveling system for vampires a long time ago.
