### ISSUE TITLE
Add Blood Jars

### ISSUE THREAD

**Issue by Avasam** [MassiveCraft/Vampire#78]
I think it would be nice if we could transport blood in form of jars (custom potion much like holy water). This way vampires could bring their food with them!

It would also be awesome if somewhere in the config we could add IDs/item names for bloodj from mods like Bloodmagic or Necromancy. (It's kinda ironic/annoying to have the so said blood jar in your hand and you can't drink it)

**Comment by ulumulu1510** [comment]
Implemented by Blanclour
