### ISSUE TITLE
My numerous requests

### ISSUE THREAD

**Issue by NicolaIlKiller** [MassiveCraft/Vampire#79]
I was wondering if you could put: 
1) a system to "inject" the infected blood to the victim without her consent 
2) a system for not sucking the blood of the victim in combat 
3) a system to choose if infect the victim when a vampire sucks his blood 
4) a hunger bar that is not static, to make more real the needs of a vampire 
5) a command to heal a player
6) add the bat form
I'm sorry to disturb you, for my bad english (I'm Italian) and my numerous requests.

**Comment by ulumulu1510** [comment]
Most of those requests are either duplicates or already available in config. - Closing
