### ISSUE TITLE
status info lists uuid instead of player name

### ISSUE THREAD

**Issue by intangir** [MassiveCraft/Vampire#82]
i notice that uuid to player name info is cached, can it be used in the status info when it tells you who infected you?

**Comment by ulumulu1510** [comment]
The uuid will always translate to the current name used in the info list. If you really really need the uuid then, use the name uuid fetcher mojang provides.

**Comment by intangir** [comment]
i just noticed this old commect, i think you misunderstood what i was saying the issue was, it says the UUID in game for who infected you, instead of their player name, it would ideally say the playername, but it was saying the UUID

i haven't checked if this was fixed since, im using an older version still
