### ISSUE TITLE
Certain monsters still attacking vampires

### ISSUE THREAD

**Issue by Mseres** [MassiveCraft/Vampire#86]
Hi mobs like silverfish, witches, and a few other still attack vampires.. Please fix this bug!

**Comment by oloflarsson** [comment]
Have you tried resetting your Vampire config file?

**Comment by Mseres** [comment]
I don't have a Vampire config, and I don't think that will help anyways

**Comment by oloflarsson** [comment]
Everyone has a Vampire configuration file.

**Comment by ulumulu1510** [comment]
Issue is non-existant.
