### ISSUE TITLE
Buff the vampires, or nerf the stake.

### ISSUE THREAD

**Issue by TheBiscuitBandit** [MassiveCraft/Vampire#88]
I understand that stakes are supposed to be realised, but couldn't you add a difficult crafting recipe to make a stake? As of now, any noob can pick up a stick and easily kill fully geared vampires. Combine the easy death with burning during half of the day - vampires are weaker than humans. Especially considering the buffs they get are minimal and effectively useless.

**Comment by XlchosenonelX** [comment]
yes plz fix this

**Comment by XlchosenonelX** [comment]
only thing vamps are good for in this plugin is mineing =/

**Comment by magnusulf** [comment]
Change the configuration file to your liking. That is why we have it.
