### ISSUE TITLE
Remove Separate permissions

### ISSUE THREAD

**Issue by wazzupp11** [MassiveCraft/Vampire#91]
Can someone please explain how to remove a permission from anyone who turns into a vampire. I want to remove the permission "magicspells.*" if at all possible. Thanks

**Comment by meganmorgangames** [comment]
I would love to know how to do this as well, or if anyone is familiar with both plugins and knows how to make certain spells work with vampires only, and certain spells not work with vampires.  Assuming that permissions aren't possible.

**Comment by magnusulf** [comment]
One could listen to this event: https://github.com/MassiveCraft/Vampire/blob/master/src/com/massivecraft/vampire/event/EventVampirePlayerVampireChange.java
and change permissions when someone turns into a vampire.
