### ISSUE TITLE
Glowstone Dropping Block Instead of Dust

### ISSUE THREAD

**Issue by Zofc** [MassiveCraft/Vampire#94]
Issue: Breaking the glowstone block drops another glowstone block, and not glowstone dust.

Versions: 
Spigot-f630541-a625e45 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT
MassiveCore v2.8.19
Vampire v2.8.19

I've narrowed this down to the Vampires plugin specifically. I removed all of my other plugins (except MassiveCore) to confirm.

**Comment by ulumulu1510** [comment]
This is not a bug, it is a highly wanted feature. IF you would have read the configuration,  you would have seen that there is list called "DropSelfMaterials". In there, you will find glowstone. Please read the configuration before filing in a bug report.

**Comment by Zofc** [comment]
I apologize for not finding this configuration nested in "/..mstore/vampire_uconf@default/instance.json." Thank you for your prompt response.

**Comment by MarkehMe** [comment]
Great! Here are some additional resources that can help you out - let us know if you need more help 😁 

* https://www.massivecraft.com/vampire
* https://www.massivecraft.com/vampire-owner
