### ISSUE TITLE
Vampires 2.8.20 Cobweb issue

### ISSUE THREAD

**Issue by GoadingGoat** [MassiveCraft/Vampire#97]
When a Cobweb is broken with a sword it returns a cobweb instead of string. Assuming this is a bug, but i guess it could be a feature.

**Comment by GoadingGoat** [comment]
Ok, nevermind. This is a feature, and can be changed in the config file

**Comment by ulumulu1510** [comment]
If you read the documentation,  you would indeed see that this is a feature. But you can configure it differently, if you wish so. Just take a look at mstore/vampire_mconf and see where you can find the field which includes cobweb
